openapi: 3.0.1
info:
  title: Swagger CNC32
  description: 'This document aim to present all CNC32 API'
  termsOfService: http://swagger.io/terms/
  contact:
    email: yroffin@gmail.com
  license:
    name: MIT License
    url: https://raw.githubusercontent.com/yroffin/grbl-cnc32/master/LICENSE
  version: 1.0.0
externalDocs:
  description: No data
  url: https://github.com/yroffin/grbl-cnc32
servers:
- url: http://localhost:8080/api
tags:
- name: configuration
  description: All configuration
  externalDocs:
    description: No data
    url: https://github.com/yroffin/grbl-cnc32
- name: i18n
  description: All i18n related
- name: misc
  description: All misc related
paths:
  /v1/config/config.json:
    put:
      tags:
      - configuration
      summary: Update configuration
      operationId: put-configuration
      requestBody:
        description: Object for update operation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Configuration'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configuration'
    get:
      tags:
      - configuration
      summary: Get configuration
      operationId: get-configuration
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configuration'
  /v1/i18n/i18n_enUS.json:
    put:
      tags:
      - i18n
      summary: Update i18n enUS
      operationId: put-i18n-enUS
      requestBody:
        description: Object for update operation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/i18n'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/i18n'
    get:
      tags:
      - i18n
      summary: Get i18n enUS
      operationId: get-i18n-enUS
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configuration'
  /v1/i18n/i18n_frFR.json:
    put:
      tags:
      - i18n
      summary: Update i18n frFR
      operationId: put-i18n-frFR
      requestBody:
        description: Object for update operation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/i18n'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/i18n'
    get:
      tags:
      - i18n
      summary: Get i18n frFR
      operationId: get-i18n-frFR
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Configuration'
  /v1/reboot:
    get:
      tags:
      - misc
      summary: Reboot
      operationId: reboot
      responses:
        200:
          description: successful operation
components:
  schemas:
    Configuration:
      type: object
      properties:
        sys:
          type: object
          properties:
            lang:
              type: string
        wifi:
          type: array
          items:
            properties:
              ssid:
                type: string
              pass:
                type: string
        widget:
          properties:
            background:
              type: integer
            selectedBackground:
              type: integer
            fontNormal:
              type: integer
            fontSelected:
              type: integer
            border:
              type: integer
        status:
          properties:
            busyStateFgColor:
              type: integer
            busyStateBgColor:
              type: integer
            busyStateBgColorWarn:
              type: integer
            writeStatusFgColor:
              type: integer
            writeStatusBgColor:
              type: integer
            writeStatusBgColorWarn:
              type: integer
        nunchuk:
          properties:
            calibrate:
              properties:
                x:
                  type: string
                y:
                  type: string
        grbl:
          properties:
            emulate:
              type: boolean
        tft:
          properties:
            background:
              type: integer
            calcColor:
              type: integer
            calibrate:
              type: array
              items:
                type: integer
        commands:
          properties:
            sample-001:
              type: array
              items:
                type: string
    i18n:
      type: object
      properties:
        key:
          type: object
          properties:
            key:
              type: string
